#!/bin/bash
# ============================================================
# ToleMate deployment script for cPanel shared hosting
# Domain: tolemate.kitetool.com  (single domain for web + API)
#
# Usage (on the server, inside the cloned repo):
#   chmod +x deploy.sh
#   ./deploy.sh            # pulls the latest 'new' branch, then deploys
#   SKIP_PULL=1 ./deploy.sh   # deploy what is already checked out
#
# Assumes:
#   - PHP 8.2+ selected for the subdomain (cPanel MultiPHP)
#   - MySQL database vertexen_tolemate already created in cPanel
#   - Subdomain document root points to: ~/public_html/tolemate/backend/public
#   - SSH access (Terminal / SSH Terminal in cPanel)
# ============================================================
set -e
cd "$(dirname "$0")"

echo "==> ToleMate deploy started ($(date))"

# ---------- Pull latest code ----------
# frontend/build is tracked in git AND regenerated by step 4 when Node is
# available, so a previous deploy leaves it modified and would block the
# pull. It is a generated folder, so reset it before pulling. After the
# pull, re-exec this script (once) so we run the NEW deploy.sh rather than
# the old copy bash already has half-read.
if [ -z "$SKIP_PULL" ] && [ -z "$DEPLOY_PULLED" ] && [ -d .git ]; then
    echo "==> Pulling latest code..."
    git checkout -- frontend/build 2>/dev/null || true
    git pull --ff-only
    export DEPLOY_PULLED=1
    exec bash "$0" "$@"
fi

# ---------- 0. Find a real PHP CLI binary ----------
# On some cPanel hosts the "php" in PATH resolves to the CGI/FastCGI SAPI,
# not the CLI one - artisan then silently no-ops (prints the help screen
# and CGI headers instead of running). Probe candidates and pick the first
# one that actually reports "(cli)".
find_php_cli() {
    local candidates=(
        "$HOME/bin/php"
        /opt/cpanel/ea-php84/root/usr/bin/php
        /opt/cpanel/ea-php83/root/usr/bin/php
        /opt/cpanel/ea-php82/root/usr/bin/php
        /opt/cpanel/ea-php81/root/usr/bin/php
        /usr/local/bin/php
        php
    )
    for c in "${candidates[@]}"; do
        if command -v "$c" >/dev/null 2>&1 && "$c" -v 2>/dev/null | grep -qi '(cli)'; then
            echo "$c"
            return 0
        fi
    done
    return 1
}

if PHP_BIN=$(find_php_cli); then
    echo "==> Using PHP CLI: $PHP_BIN ($($PHP_BIN -v | head -n1))"
else
    echo "!! Could not find a PHP CLI binary (only found CGI/FastCGI php)."
    echo "!! In cPanel, set up 'MultiPHP Manager' / a CLI PHP alias for this"
    echo "!! account (usually /opt/cpanel/ea-phpXX/root/usr/bin/php), then"
    echo "!! add its path to the candidates list at the top of this script."
    exit 1
fi

# ---------- 1. Backend dependencies ----------
echo "==> Installing backend dependencies..."
cd backend
if [ ! -f composer.phar ] && ! command -v composer >/dev/null 2>&1; then
    echo "    Downloading composer..."
    curl -sS https://getcomposer.org/installer | "$PHP_BIN"
    COMPOSER="$PHP_BIN composer.phar"
else
    COMPOSER="composer"
fi
$COMPOSER install --no-dev --optimize-autoloader --no-interaction

# ---------- 2. Storage + permissions ----------
echo "==> Linking storage..."
"$PHP_BIN" artisan storage:link || true
chmod -R 775 storage bootstrap/cache
chmod -R 775 storage/app/public 2>/dev/null || true

# ---------- 3. Database ----------
echo "==> Running migrations + seeders..."
"$PHP_BIN" artisan migrate --force
"$PHP_BIN" artisan db:seed --force

# ---------- 4. Web frontend ----------
echo "==> Preparing web frontend..."
cd ../frontend
if command -v node >/dev/null 2>&1; then
    echo "    Building frontend with Node..."
    npm install --no-audit --no-fund
    npm run build
else
    echo "!! No Node.js on this server - cannot rebuild the frontend."
    echo "!! Build it locally (cd frontend && npm run build), commit the"
    echo "!! updated build/ folder, then re-run this script."
fi

# The live document root is backend/public (Laravel serves the SPA shell
# dynamically via PrerenderController, which reads frontend/build/index.html
# straight off disk for SEO injection, and serves /robots.txt dynamically
# too via routes/web.php). Static assets referenced by that HTML (JS/CSS
# bundles, manifest, icons) must physically exist under backend/public/ to
# be servable. Sync them in, but:
#   - never touch index.php/.htaccess/storage (Laravel's own front
#     controller, rewrites, and the artisan storage:link symlink)
#   - never leave index.html or robots.txt as static files here - CRA's
#     defaults would shadow Laravel's dynamic routes for both (Apache
#     serves a matching real file before ever reaching PHP)
echo "==> Syncing frontend build into backend/public..."
cd ../backend
if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete \
        --exclude 'index.php' \
        --exclude '.htaccess' \
        --exclude 'index.html' \
        --exclude 'robots.txt' \
        --exclude 'backend' \
        --exclude 'storage' \
        ../frontend/build/ ./public/
else
    find ../frontend/build -mindepth 1 -maxdepth 1 \
        ! -name 'index.php' ! -name '.htaccess' ! -name 'index.html' ! -name 'robots.txt' ! -name 'backend' ! -name 'storage' \
        -exec cp -r {} ./public/ \;
fi
rm -f ./public/index.html ./public/robots.txt

# ---------- 5. Laravel caches ----------
echo "==> Optimizing Laravel..."
"$PHP_BIN" artisan config:cache
"$PHP_BIN" artisan route:cache
"$PHP_BIN" artisan view:cache
"$PHP_BIN" artisan optimize

# ---------- 6. Sanity checks ----------
echo "==> Checking AI agent routes are registered..."
if "$PHP_BIN" artisan route:list 2>/dev/null | grep -q "ai-agent/chat/stream"; then
    echo "    OK: /api/ai-agent/* routes present"
else
    echo "!! ai-agent routes NOT found - the pull may not have brought them in."
fi
if grep -rq "ai-agent/chat/stream" ../frontend/build/static/js/ 2>/dev/null; then
    echo "    OK: web bundle contains the streaming chat widget"
else
    echo "!! web bundle is missing the streaming widget (stale frontend/build)."
fi
echo "    Reminder: in Admin > Connect AI Agent set the agent URL + API key;"
echo "    the URL must be reachable from this server (not localhost on your PC)."

echo "==> Done! https://tolemate.kitetool.com should be live."
echo "    Super admin: superadmin@tolemate.com / password"
