import React from 'react';
import SeoHead from '../components/SeoHead';
import { useSettings } from '../context/SettingsContext';

const PrivacyPolicy: React.FC = () => {
  const { getSetting } = useSettings();
  const siteName = getSetting('site_name', 'ToleMate');
  const contactEmail = getSetting('contact_email', 'info@tolemate.com');

  return (
    <>
      <SeoHead title="Privacy Policy" description={`How ${siteName} collects, uses, and protects your data.`} canonicalUrl={window.location.href} />
      <div className="max-w-3xl mx-auto px-4 py-14">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Privacy Policy</h1>
        <p className="text-sm text-gray-400 mb-8">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long' })}</p>
        <div className="prose prose-gray max-w-none space-y-6 text-gray-600 leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">Information we collect</h2>
            <p>We collect information you provide directly, such as your name, email, phone number, and location, when you register, book a service, or contact us. We also collect information generated by using the platform, such as bookings, messages, and reviews.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">How we use your information</h2>
            <p>We use your information to operate the marketplace: matching customers with vendors, processing bookings and payments, sending notifications, and improving the platform. We do not sell your personal information to third parties.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">Sharing</h2>
            <p>Information necessary to complete a booking (such as your name and contact details) is shared with the vendor you book with. We may share information with service providers who help us operate the platform (e.g. payment processors), under confidentiality obligations.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">Security</h2>
            <p>We use reasonable technical and organizational measures to protect your information. No method of transmission or storage is 100% secure, and we cannot guarantee absolute security.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">Your choices</h2>
            <p>You can update your account information at any time from your profile settings, and you can request deletion of your account by contacting us.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">Contact</h2>
            <p>Questions about this policy can be sent to <a href={`mailto:${contactEmail}`} className="text-primary-600 hover:underline">{contactEmail}</a> or via our <a href="/contact" className="text-primary-600 hover:underline">contact form</a>.</p>
          </section>
        </div>
      </div>
    </>
  );
};

export default PrivacyPolicy;
